# Generated by Django 3.0.3 on 2020-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicprofile',
            name='city_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='city_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='tel_private',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
